name: Android Testing CI
on: [push] #all branches

jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Unit Test #execute task for test of gradle
        run: ./gradlew testDebugUnitTest #integration continue do that
      - name: Android Test Report #report of the test
        use: asadmansr/android-test-report-action@v1.2.0 #android test report action library
        if: ${{ always() }} #if fails something always execute that




